// Does every screen still have a client boundary the server can find?
//
// ⚠️ **This exists because a build can succeed and serve a 500 to every
// tenant.** Moving one component into `src/app/kassa/` dropped the till page's
// own entry from its React client manifest. Nothing said so: `next build`
// printed the route at its normal size and exited 0, `tsc` was clean, and 205
// tests passed — because every one of them renders the page directly and never
// crosses the server/client boundary that was broken. The first evidence was
// twelve counters showing "Oshxonada nimadir noto'g'ri ketdi" during service.
//
// ⚠️ **It reads the artefact, not the source.** The failure was in what the
// bundler emitted, so a check on the code we wrote would have agreed with the
// code we wrote and passed. What matters is whether the file Next serves knows
// how to reach the page.
//
// Runs as part of `npm run build`, which is what the Dockerfile runs — so a
// broken manifest fails the image instead of the evening.

import { readFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

const root = ".next/server/app";
const bad = [];
let checked = 0;

/** The source file a route's page was compiled from, if we can find it. */
function pageSource(route) {
  for (const ext of ["tsx", "ts", "jsx", "js"]) {
    const p = `src/app${route}/page.${ext}`;
    if (existsSync(p)) return p;
  }
  return null;
}

/** Every route that emitted a page, with the manifest beside it. */
function walk(dir, route) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full, `${route}/${entry.name}`);
      continue;
    }
    if (entry.name !== "page_client-reference-manifest.js") continue;

    const src = pageSource(route);
    // ⚠️ **Only pages that are themselves client components.** A server page
    // has no boundary of its own and must not be reported — a guard that cries
    // about seven healthy routes is a guard somebody switches off, and then it
    // is not there for the one route that is actually broken.
    //
    // ⚠️ Next's own `_not-found` has no file in `src/app`, and neither will a
    // route generated by a future convention. Unknown means unchecked, not
    // broken.
    if (!src) continue;
    if (!/^\s*["']use client["']/.test(readFileSync(src, "utf8"))) continue;

    checked += 1;
    globalThis.__RSC_MANIFEST = {};
    // The file is written as an assignment into that global; running it is how
    // Next itself loads it.
    new Function(readFileSync(full, "utf8"))();
    const key = `${route}/page`;
    const manifest = globalThis.__RSC_MANIFEST[key];
    const modules = Object.keys(manifest?.clientModules ?? {});
    // ⚠️ **The page's own file, not merely "some client modules".** The
    // manifest is full of shared ones from the layout and from Next itself,
    // which is exactly why the missing entry was invisible: 121 names were
    // present and the only one that mattered was not.
    if (!modules.some((m) => m.endsWith(`/${src}`))) bad.push({ key, src });
  }
}

if (!existsSync(root)) {
  console.error("check-build: no build output — did next build run?");
  process.exit(1);
}
walk(root, "");

if (bad.length > 0) {
  console.error(
    `\ncheck-build: ${bad.length} client page(s) are missing from their own manifest.\n` +
      bad.map((b) => `  ${b.key}  (${b.src})`).join("\n") +
      "\n\nThese serve a 500 with an error digest and nothing in the build log.\n" +
      "A component placed in the route's own directory has caused this before;\n" +
      "moving it under src/components/ fixed it. See the note at the top of this file.\n",
  );
  process.exit(1);
}
console.log(`check-build: ${checked} client page(s) reachable from their manifest.`);
