package provision

// Putting one photograph into a tenant's uploads.
//
// ⚠️ **Through a one-shot container, for the same reason PurgeUploads is.** The
// console mounts the uploads root **read-only** — that mount is a standing
// guarantee that nothing the control plane does can write into a customer's
// files, and loosening it to make a button work would trade the guarantee for a
// convenience. Docker access is a power this process already holds; this spends
// it once, scoped to a single tenant's directory, instead of holding a
// permanent write path to every restaurant's photographs.
//
// ⚠️ **The bind is the tenant's own directory, never the root with a subpath
// appended.** A mount of the parent would give a throwaway container write
// access to every other customer's files for the length of one copy, with a
// string deciding which one is written.
//
// The bytes get in through Docker's archive endpoint, into `/tmp` — the
// container's **own** filesystem, which is what that endpoint is defined to
// write to on a container that has not started. Copying from there to the bind
// is the started container's job. Writing the archive straight at the bind path
// is the obvious shortcut and it is undefined: Docker documents `cp` into a
// volume of a stopped container as landing in the container layer, so the file
// would vanish with the container and the upload would report success.

import (
	"archive/tar"
	"bytes"
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// WriteUpload places `data` at `<uploads>/design/<name>` for one tenant.
//
// `name` is generated by the caller and must already be safe: it is
// concatenated into a shell command, so anything but a plain file name is a
// command the caller did not mean to run. Checked here as well, because the
// place a rule is enforced should be the place it cannot be skipped.
func (c *Client) WriteUpload(ctx context.Context, slug, name string, data []byte) error {
	if strings.TrimSpace(slug) == "" {
		return errors.New("slug bo'sh")
	}
	if !safeUploadName(name) {
		return fmt.Errorf("fayl nomi yaroqsiz: %q", name)
	}
	if len(data) == 0 {
		return errors.New("fayl bo'sh")
	}

	dir := strings.TrimRight(c.cfg.UploadsRoot, "/") + "/" + slug + "/uploads"
	cname := "keel-put-" + slug

	// Left over from an attempt that died mid-way; the name would otherwise be
	// taken and every retry would fail for a reason nobody can see.
	_, _ = c.do(ctx, http.MethodDelete, "/containers/"+url.PathEscape(cname)+"?force=true", nil, nil)

	body := map[string]any{
		// The tenant image, because it is the one image this host is guaranteed
		// to have. Pulling a general-purpose image here would make an ordinary
		// editing step depend on the network.
		"Image":      c.cfg.Image,
		"Entrypoint": []string{"/bin/sh", "-c"},
		// ⚠️ `-f` on the move, so re-uploading over a name that exists replaces
		// it rather than leaving the old picture in place and reporting success.
		"Cmd": []string{
			"mkdir -p /target/design && mv -f /tmp/" + name + " /target/design/" + name +
				" && chmod 644 /target/design/" + name,
		},
		"HostConfig": map[string]any{
			"Binds":      []string{dir + ":/target"},
			"AutoRemove": false,
			// ⚠️ No network at all: this container copies a file. Anything it
			// could reach, it has no business reaching.
			"NetworkMode": "none",
			"Memory":      int64(64) << 20,
		},
	}
	if _, err := c.do(ctx, http.MethodPost, "/containers/create?name="+url.QueryEscape(cname), body, nil); err != nil {
		return err
	}
	// ⚠️ Removed whatever happens below. `AutoRemove` cannot be relied on here:
	// a container that fails before it starts is never reaped by it, and the
	// next upload would find the name taken.
	defer func() {
		ctx, cancel := context.WithTimeout(context.Background(), 20*time.Second)
		defer cancel()
		_, _ = c.do(ctx, http.MethodDelete, "/containers/"+url.PathEscape(cname)+"?force=true", nil, nil)
	}()

	tarball, err := singleFileTar(name, data)
	if err != nil {
		return err
	}
	if err := c.putArchive(ctx, cname, "/tmp", tarball); err != nil {
		return err
	}
	if _, err := c.do(ctx, http.MethodPost, "/containers/"+url.PathEscape(cname)+"/start", nil, nil); err != nil {
		return err
	}
	// Waited for rather than fired and forgotten: "the picture is there" is the
	// one claim here that must not be a guess — the editor is about to point a
	// design at this path.
	var res struct {
		StatusCode int `json:"StatusCode"`
	}
	if _, err := c.do(ctx, http.MethodPost, "/containers/"+url.PathEscape(cname)+"/wait", nil, &res); err != nil {
		return err
	}
	if res.StatusCode != 0 {
		return fmt.Errorf("rasmni yozish %d bilan tugadi", res.StatusCode)
	}
	return nil
}

// putArchive uploads a tar into a container's own filesystem.
//
// Its own function because `do` marshals JSON, and this body is a tar.
func (c *Client) putArchive(ctx context.Context, name, dest string, tarball []byte) error {
	path := "/containers/" + url.PathEscape(name) + "/archive?path=" + url.QueryEscape(dest)
	req, err := http.NewRequestWithContext(ctx, http.MethodPut,
		"http://docker"+path, bytes.NewReader(tarball))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/x-tar")
	res, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("docker: ulanib bo'lmadi (%s): %w", c.cfg.Socket, err)
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 {
		return fmt.Errorf("docker archive: HTTP %d", res.StatusCode)
	}
	return nil
}

// singleFileTar wraps one file so Docker's archive endpoint can take it.
func singleFileTar(name string, data []byte) ([]byte, error) {
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	hdr := &tar.Header{
		Name:    name,
		Mode:    0o644,
		Size:    int64(len(data)),
		ModTime: time.Now(),
	}
	if err := tw.WriteHeader(hdr); err != nil {
		return nil, err
	}
	if _, err := tw.Write(data); err != nil {
		return nil, err
	}
	if err := tw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// safeUploadName accepts only a plain file name.
//
// ⚠️ **This value is concatenated into a shell command**, so the question is
// not "is it a tidy name" but "can it be anything other than a name". A slash
// escapes the directory, a quote or a semicolon ends the argument and starts a
// command, and a leading dash turns it into a flag. The allowlist is letters,
// digits, dash, underscore and one dot.
func safeUploadName(name string) bool {
	if name == "" || len(name) > 64 || strings.HasPrefix(name, "-") || strings.HasPrefix(name, ".") {
		return false
	}
	dots := 0
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
		case r == '-', r == '_':
		case r == '.':
			dots++
		default:
			return false
		}
	}
	return dots == 1
}
